import axios from "axios";

const nameAndPoster = {
  page: 1,
  page_size: 24,
  total_pages: 83,
  total_results: 27711,
  items: [
    {
      jw_entity_id: "tm817661",
      id: 817661,
      title: "모가디슈",
      full_path: "/kr/영화/mogadisyu",
      poster: "/poster/247509899/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm146588",
      id: 146588,
      title: "타임 패러독스",
      full_path: "/kr/영화/predestination",
      poster: "/poster/188268532/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm305113",
      id: 305113,
      title: "듄",
      full_path: "/kr/영화/dyun",
      poster: "/poster/251148698/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm313044",
      id: 313044,
      title: "베놈",
      full_path: "/kr/영화/benom",
      poster: "/poster/245637413/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm205861",
      id: 205861,
      title: "컨택트",
      full_path: "/kr/영화/keontaegteu",
      poster: "/poster/130964237/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm460711",
      id: 460711,
      title: "프리 가이",
      full_path: "/kr/영화/peuri-gai",
      poster: "/poster/253033499/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm232799",
      id: 232799,
      title: "007 노 타임 투 다이",
      full_path: "/kr/영화/007-no-taim-tu-dai",
      poster: "/poster/251148716/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm457652",
      id: 457652,
      title: "베놈 2: 렛 데어 비 카니지",
      full_path: "/kr/영화/benom-2-res-deeo-bi-kaniji",
      poster: "/poster/249817089/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm821207",
      id: 821207,
      title: "샹치와 텐 링즈의 전설",
      full_path: "/kr/영화/syangci-aen-deo-rejeondeu-obeu-deo-ten-ringjeu",
      poster: "/poster/249642135/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm455670",
      id: 455670,
      title: "테넷",
      full_path: "/kr/영화/tenes",
      poster: "/poster/193792450/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm166964",
      id: 166964,
      title: "듄",
      full_path: "/kr/영화/sagu",
      poster: "/poster/8927089/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm855323",
      id: 855323,
      title: "노매드랜드",
      full_path: "/kr/영화/nomaedeuraendeu",
      poster: "/poster/244575124/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm93739",
      id: 93739,
      title: "그을린 사랑",
      full_path: "/kr/영화/geueulrin-sarang",
      poster: "/poster/19648719/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm240625",
      id: 240625,
      title: "크루엘라",
      full_path: "/kr/영화/keuruelra",
      poster: "/poster/245308901/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm424851",
      id: 424851,
      title: "작은 아씨들",
      full_path: "/kr/영화/jageun-assideul",
      poster: "/poster/165122548/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm225321",
      id: 225321,
      title: "레디 플레이어 원",
      full_path: "/kr/영화/redi-peulreieo-weon",
      poster: "/poster/50902721/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm852712",
      id: 852712,
      title: "그린 나이트",
      full_path: "/kr/영화/geurin-naiteu",
      poster: "/poster/248826704/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm863227",
      id: 863227,
      title: "듄: 드리프터",
      full_path: "/kr/영화/dyun-deuripeuteo",
      poster: "/poster/243933567/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm350086",
      id: 350086,
      title: "레이니 데이 인 뉴욕",
      full_path: "/kr/영화/reini-dei-in-nyuyog",
      poster: "/poster/176171073/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm1046627",
      id: 1046627,
      title: "잠든 여인",
      full_path: "/kr/영화/hypnotic",
      poster: "/poster/254094864/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm439797",
      id: 439797,
      title: "블랙 위도우",
      full_path: "/kr/영화/beulraeg-widou",
      poster: "/poster/254317024/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm360066",
      id: 360066,
      title: "리듬 오브 리벤지",
      full_path: "/kr/영화/rideum-obeu-ribenji",
      poster: "/poster/177215033/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm826531",
      id: 826531,
      title: "싱크홀",
      full_path: "/kr/영화/singkeuhol",
      poster: "/poster/248797129/{profile}",
      object_type: "movie",
    },
    {
      jw_entity_id: "tm344989",
      id: 344989,
      title: "레이디 버드",
      full_path: "/kr/영화/reidi-beodeu",
      poster: "/poster/203760972/{profile}",
      object_type: "movie",
    },
  ],
};
const genreInfo = [
  {
    id: 1,
    short_name: "act",
    technical_name: "action",
    translation: "액션",
    slug: "aegsyeon",
  },
  {
    id: 2,
    short_name: "ani",
    technical_name: "animation",
    translation: "애니메이션",
    slug: "aenimeisyeon",
  },
  {
    id: 3,
    short_name: "cmy",
    technical_name: "comedy",
    translation: "코미디",
    slug: "komidi",
  },
  {
    id: 4,
    short_name: "crm",
    technical_name: "crime",
    translation: "범죄",
    slug: "beomjoe",
  },
  {
    id: 5,
    short_name: "doc",
    technical_name: "documentation",
    translation: "다큐멘터리",
    slug: "dakyumenteori",
  },
  {
    id: 6,
    short_name: "drm",
    technical_name: "drama",
    translation: "드라마",
    slug: "deurama",
  },
  {
    id: 7,
    short_name: "fnt",
    technical_name: "fantasy",
    translation: "판타지",
    slug: "pantaji",
  },
  {
    id: 8,
    short_name: "hst",
    technical_name: "history",
    translation: "역사",
    slug: "yeogsa",
  },
  {
    id: 9,
    short_name: "hrr",
    technical_name: "horror",
    translation: "공포",
    slug: "gongpo",
  },
  {
    id: 10,
    short_name: "fml",
    technical_name: "family",
    translation: "가족",
    slug: "gajog",
  },
  {
    id: 11,
    short_name: "msc",
    technical_name: "music",
    translation: "음악",
    slug: "eumag",
  },
  {
    id: 12,
    short_name: "trl",
    technical_name: "thriller",
    translation: "스릴러",
    slug: "seurilreo",
  },
  {
    id: 13,
    short_name: "rma",
    technical_name: "romance",
    translation: "로맨스",
    slug: "romaenseu",
  },
  {
    id: 14,
    short_name: "scf",
    technical_name: "scifi",
    translation: "SF",
    slug: "sf",
  },
  {
    id: 15,
    short_name: "spt",
    technical_name: "sport",
    translation: "스포츠",
    slug: "seupoceu",
  },
  {
    id: 16,
    short_name: "war",
    technical_name: "war",
    translation: "전쟁",
    slug: "jeonjaeng",
  },
  {
    id: 17,
    short_name: "wsn",
    technical_name: "western",
    translation: "서부",
    slug: "seobu",
  },
  {
    id: 23,
    short_name: "rly",
    technical_name: "reality",
    translation: "Reality TV",
    slug: "reality-tv",
  },
  {
    id: 18,
    short_name: "eur",
    technical_name: "european",
    translation: "Made in Europe",
    slug: "made-in-europe",
  },
];
const platfromInfo = [
  {
    id: 8,
    technical_name: "netflix",
    short_name: "nfx",
    clear_name: "Netflix",
    icon_url: "\u002Ficon\u002F207360008\u002F{profile}",
  },
  {
    id: 119,
    technical_name: "amazonprimevideo",
    short_name: "prv",
    clear_name: "Amazon Prime Video",
    icon_url: "\u002Ficon\u002F52449861\u002F{profile}",
  },
  {
    id: 337,
    technical_name: "disneyplus",
    short_name: "dnp",
    clear_name: "Disney Plus",
    icon_url: "\u002Ficon\u002F147638351\u002F{profile}",
  },
  {
    id: 356,
    technical_name: "wavve",
    short_name: "wav",
    clear_name: "wavve",
    icon_url: "\u002Ficon\u002F155655742\u002F{profile}",
  },
  {
    id: 97,
    technical_name: "watcha",
    short_name: "wac",
    clear_name: "Watcha",
    icon_url: "\u002Ficon\u002F2538290\u002F{profile}",
  },
  {
    id: 350,
    technical_name: "appletvplus",
    short_name: "atp",
    clear_name: "Apple TV Plus",
    icon_url: "\u002Ficon\u002F152862153\u002F{profile}",
  },
  {
    id: 96,
    technical_name: "naverstore",
    short_name: "nvs",
    clear_name: "Naver Store",
    icon_url: "\u002Ficon\u002F2538289\u002F{profile}",
  },
  {
    id: 3,
    technical_name: "play",
    short_name: "ply",
    clear_name: "Google Play Movies",
    icon_url: "\u002Ficon\u002F169478387\u002F{profile}",
  },
  {
    id: 11,
    technical_name: "mubi",
    short_name: "mbi",
    clear_name: "Mubi",
    icon_url: "\u002Ficon\u002F164970114\u002F{profile}",
  },
  {
    id: 100,
    technical_name: "guidedoc",
    short_name: "gdc",
    clear_name: "GuideDoc",
    icon_url: "\u002Ficon\u002F2625277\u002F{profile}",
  },
  {
    id: 101,
    technical_name: "daum",
    short_name: "dam",
    clear_name: "Daum",
    icon_url: "\u002Ficon\u002F2655283\u002F{profile}",
  },
  {
    id: 98,
    technical_name: "megabox",
    short_name: "mbx",
    clear_name: "Megabox",
    icon_url: "\u002Ficon\u002F2539917\u002F{profile}",
    icon_blur_hash: "KIRMe]xv?a%Mjaj[?@oeMz",
  },
  {
    id: 283,
    technical_name: "crunchyroll",
    short_name: "cru",
    clear_name: "Crunchyroll",
    icon_url: "\u002Ficon\u002F127445869\u002F{profile}",
  },
  {
    id: 190,
    technical_name: "curiositystream",
    short_name: "cts",
    clear_name: "Curiosity Stream",
    icon_url: "\u002Ficon\u002F48600036\u002F{profile}",
  },
  {
    id: 521,
    technical_name: "spamflix",
    short_name: "sfx",
    clear_name: "Spamflix",
    icon_url: "\u002Ficon\u002F240831409\u002F{profile}",
  },
  {
    id: 475,
    technical_name: "docsville",
    short_name: "dsv",
    clear_name: "DOCSVILLE",
    icon_url: "\u002Ficon\u002F208148387\u002F{profile}",
  },
  {
    id: 538,
    technical_name: "plex",
    short_name: "plx",
    clear_name: "Plex",
    icon_url: "\u002Ficon\u002F243059301\u002F{profile}",
  },
  {
    id: 546,
    technical_name: "wowpresentsplus",
    short_name: "wow",
    clear_name: "WOW Presents Plus",
    icon_url: "\u002Ficon\u002F243229654\u002F{profile}",
  },
  {
    id: 551,
    technical_name: "magellantv",
    short_name: "mgl",
    clear_name: "Magellan TV",
    icon_url: "\u002Ficon\u002F243233518\u002F{profile}",
  },
  {
    id: 554,
    technical_name: "broadwayhd",
    short_name: "bhd",
    clear_name: "BroadwayHD",
    icon_url: "\u002Ficon\u002F243239329\u002F{profile}",
  },
  {
    id: 559,
    technical_name: "filmzie",
    short_name: "fmz",
    clear_name: "Filmzie",
    icon_url: "\u002Ficon\u002F243251295\u002F{profile}",
  },
  {
    id: 444,
    technical_name: "dekkoo",
    short_name: "dkk",
    clear_name: "Dekkoo",
    icon_url: "\u002Ficon\u002F202068207\u002F{profile}",
  },
  {
    id: 567,
    technical_name: "truestory",
    short_name: "trs",
    clear_name: "True Story",
    icon_url: "\u002Ficon\u002F244289819\u002F{profile}",
  },
  {
    id: 569,
    technical_name: "dafilms",
    short_name: "daf",
    clear_name: "DocAlliance Films",
    moneticon_url: "\u002Ficon\u002F244290074\u002F{profile}",
  },
  {
    id: 315,
    technical_name: "hoichoi",
    short_name: "hoc",
    clear_name: "Hoichoi",
    icon_url: "\u002Ficon\u002F141253805\u002F{profile}",
  },
];

export const getDetailData = () => {
  return axios.get(
    "https://apis.justwatch.com/content/titles/movie/432043/locale/ko_KR?language=ko"
  );
};
